"""
Model for an embedding vector generated from a document chunk.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Any, Optional
from .base_entity import BaseEntity


@dataclass
class EmbeddingVector(BaseEntity):
    """
    Represents a numerical representation of a document chunk generated by Cohere models.
    """
    vector: List[float] = field(default_factory=list)
    document_chunk_id: str = ""
    metadata: Optional[Dict[str, Any]] = None

    def __post_init__(self):
        """Initialize any additional attributes after construction."""
        super().__post_init__()
        if self.metadata is None:
            self.metadata = {}